spring:
  application:
    name: Boardly
  datasource:
    url: jdbc:postgresql://localhost:5432/boardly_db
    username: boardly_user
    password: boardly_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      add-mappings: true
  data:
    mongodb:
      uri: mongodb://boardly_user:boardly_pass@localhost:27017/boardly_kanban?authSource=admin

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.boardly: DEBUG

server:
  port: 8080

jwt:
  secret: Wz9a8K6N4b8qX0gF3x9Z+9G8sK5R7EoKq8l0kT6C4Q=
  expiration: 36000

api:
  base-path: /api
  version: v1