spring:
  application:
    name: Boardly
  datasource:
    url: jdbc:postgresql://localhost:5432/boardly_db
    username: boardly_user
    password: boardly_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      add-mappings: true
  data:
    mongodb:
      uri: mongodb://boardly_user:boardly_pass@localhost:27017/boardly_kanban?authSource=admin
  mail:
    host: "smtp.example.com"
    port: 587
    username: "your-email@example.com"
    password: "your-password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.boardly: DEBUG

server:
  port: 8080

jwt:
  secret: Wz9a8K6N4b8qX0gF3x9Z+9G8sK5R7EoKq8l0kT6C4Q=
  access_token_expiration: 900000
  refresh_token_expiration: 2592000000

api:
  base-path: /api
  version: v1

app:
  frontend:
    url: "http://localhost:3000"
