spring:
  application:
    name: Boardly
  datasource:
    url: jdbc:postgresql://localhost:5432/boardly_db
    username: boardly_user
    password: boardly_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080